# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductCategory', models.CharField(max_length=100)),
                ('ProductTotalScore', models.IntegerField()),
                ('NumberofReviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewScore', models.IntegerField()),
                ('ProductName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddWater.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.CharField(max_length=100)),
            ],
        ),
    ]
