# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddWater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('ProductName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddWater.Products')),
            ],
        ),
    ]
