# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 06:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AddWater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductFlavor', models.CharField(max_length=15)),
                ('ProductName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddWater.Products')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
