# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddWater', '0002_auto_20170503_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductCategory',
            field=models.CharField(choices=[('Sparkling', 'Sparkling'), ('Flat', 'Flat')], max_length=9),
        ),
    ]
