# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddWater', '0003_auto_20170504_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavors',
            name='ProductFlavor',
            field=models.CharField(max_length=15),
        ),
    ]
